services:
  api-gym:
    image: ${IMAGE_NAME}:latest
    container_name: gym_backend
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db-gym;Port=5432;Database=gym_db;Username=postgres;Password=user123$
    ports:
      - "8080:8080"
    depends_on:
      - db-gym 

  db-gym:
    image: postgres:15-alpine
    container_name: gym_db
    user: "1000:1000"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user123$
      POSTGRES_DB: gym_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres_data:/var/lib/postgresql/data